# POSTTEST 7 PRAKTIKUM KECERDASAN BUATAN
### NAMA  : RISMAYANTI
### NIM    : 2109106025
### KELAS : A1-21

## Mengimport Library 

In [104]:
import tensorflow as tf

## 1. Membuat sebuah tensor shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [105]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-0.9760397 , -0.7149236 ,  0.73386455,  0.28581223, -0.02302803],
       [ 0.6578604 ,  0.40351585, -1.0177003 ,  1.5687829 ,  1.3205584 ],
       [-1.0235384 ,  0.40732396,  0.46989402,  0.6069317 ,  0.75923777],
       [-1.4553891 , -0.9280767 ,  2.209676  , -0.05317732, -0.4817062 ],
       [ 0.00569245,  1.4055637 , -0.31561458,  0.01160778, -0.3512627 ]],
      dtype=float32)

## 2. Membuat sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor

In [106]:
prime_tensor = tf.constant([2, 3, 5, 7, 11, 
                            13, 17, 19, 23, 29,
                            31, 37, 41, 43, 47, 
                            53, 59, 61, 67, 71, 
                            73, 79, 83, 89, 97], shape=[5,5], dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 67., 71.],
       [73., 79., 83., 89., 97.]], dtype=float32)

## 3. Menampilkan Dimensi Kedua Variable

### Menampilkan Dimensi Variable random_tensor

In [107]:
dim_display_random = tf.constant(['random_tensor'], shape=[5,5])
dim_display_random.shape


TensorShape([5, 5])

In [108]:
tf.shape(dim_display_random)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

### Menampilkan Dimensi Variable prime_tensor

In [109]:
dim_display_prime = tf.constant(['prime_tensor'], shape=[5,5])
dim_display_prime.shape

TensorShape([5, 5])

In [110]:
tf.shape(dim_display_random)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5])>

## 4. Menampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

### Operator Penjumlahan

In [111]:
print("HASIL PENJUMLAHAN DARI RANDOM_TENSOR & PRIME_TENSOR : ")
penjumlahan = random_tensor + prime_tensor
penjumlahan.numpy()

HASIL PENJUMLAHAN DARI RANDOM_TENSOR & PRIME_TENSOR : 


array([[ 1.0239604,  2.2850764,  5.733865 ,  7.2858124, 10.976972 ],
       [13.657861 , 17.403517 , 17.9823   , 24.568783 , 30.320559 ],
       [29.976461 , 37.407326 , 41.469894 , 43.606934 , 47.75924  ],
       [51.54461  , 58.071922 , 63.209675 , 66.94682  , 70.518295 ],
       [73.00569  , 80.40556  , 82.68439  , 89.011604 , 96.648735 ]],
      dtype=float32)

### Operator Pengurangan

In [112]:
print("HASIL PENGURANGAN DARI RANDOM_TENSOR & PRIME_TENSOR : ")
pengurangan = random_tensor - prime_tensor
pengurangan.numpy()

HASIL PENGURANGAN DARI RANDOM_TENSOR & PRIME_TENSOR : 


array([[ -2.9760396,  -3.7149236,  -4.266135 ,  -6.7141876, -11.023028 ],
       [-12.342139 , -16.596483 , -20.0177   , -21.431217 , -27.679441 ],
       [-32.023537 , -36.592674 , -40.530106 , -42.393066 , -46.24076  ],
       [-54.45539  , -59.928078 , -58.790325 , -67.05318  , -71.481705 ],
       [-72.99431  , -77.59444  , -83.31561  , -88.988396 , -97.351265 ]],
      dtype=float32)

### Operator Perkalian

In [113]:
print("HASIL PERKALIAN DARI RANDOM_TENSOR & PRIME_TENSOR : ")
perkalian = random_tensor * prime_tensor
perkalian.numpy()

HASIL PERKALIAN DARI RANDOM_TENSOR & PRIME_TENSOR : 


array([[ -1.9520794 ,  -2.1447709 ,   3.6693227 ,   2.0006857 ,
         -0.25330827],
       [  8.552185  ,   6.8597693 , -19.336306  ,  36.08201   ,
         38.296196  ],
       [-31.729689  ,  15.070987  ,  19.265656  ,  26.098063  ,
         35.684174  ],
       [-77.13563   , -54.756523  , 134.79024   ,  -3.5628805 ,
        -34.20114   ],
       [  0.41554886, 111.039536  , -26.19601   ,   1.0330925 ,
        -34.07248   ]], dtype=float32)

### Operator Pembagian

In [114]:
print("HASIL PEMBAGIAN DARI RANDOM_TENSOR & PRIME_TENSOR : ")
pembagian = random_tensor / prime_tensor
pembagian.numpy()

HASIL PEMBAGIAN DARI RANDOM_TENSOR & PRIME_TENSOR : 


array([[-4.88019854e-01, -2.38307878e-01,  1.46772906e-01,
         4.08303179e-02, -2.09345692e-03],
       [ 5.06046452e-02,  2.37362254e-02, -5.35631739e-02,
         6.82079569e-02,  4.55364957e-02],
       [-3.30173671e-02,  1.10087553e-02,  1.14608295e-02,
         1.41146900e-02,  1.61539949e-02],
       [-2.74601728e-02, -1.57301128e-02,  3.62241976e-02,
        -7.93691317e-04, -6.78459462e-03],
       [ 7.79787733e-05,  1.77919455e-02, -3.80258542e-03,
         1.30424509e-04, -3.62126483e-03]], dtype=float32)

### Operator Sisa Bagi

In [115]:
print("HASIL SISA BAGI ANTARA RANDOM_TENSOR & PRIME_TENSOR : ")
modulus = random_tensor % prime_tensor
modulus.numpy()

HASIL SISA BAGI ANTARA RANDOM_TENSOR & PRIME_TENSOR : 


array([[1.0239604e+00, 2.2850764e+00, 7.3386455e-01, 2.8581223e-01,
        1.0976972e+01],
       [6.5786040e-01, 4.0351585e-01, 1.7982300e+01, 1.5687829e+00,
        1.3205584e+00],
       [2.9976461e+01, 4.0732396e-01, 4.6989402e-01, 6.0693169e-01,
        7.5923777e-01],
       [5.1544609e+01, 5.8071922e+01, 2.2096760e+00, 6.6946823e+01,
        7.0518295e+01],
       [5.6924503e-03, 1.4055637e+00, 8.2684387e+01, 1.1607781e-02,
        9.6648735e+01]], dtype=float32)

### Operator Pangkat

In [116]:
print("HASIL PANGKAT ANTARA RANDOM_TENSOR & PRIME_TENSOR : ")
pangkat = random_tensor ** prime_tensor
pangkat.numpy()

HASIL PANGKAT ANTARA RANDOM_TENSOR & PRIME_TENSOR : 


array([[ 9.5265353e-01, -3.6540875e-01,  2.1285288e-01,  1.5579935e-04,
        -9.6565882e-19],
       [ 4.3225363e-03,  1.9935636e-07, -1.3956556e+00,  3.1473543e+04,
         3.1766621e+03],
       [-2.0569689e+00,  3.6963942e-15,  3.5644844e-14,  4.7316423e-10,
         2.3864741e-06],
       [-4.3440410e+08, -1.2230603e-02,  1.0093571e+21, -0.0000000e+00,
        -3.0028864e-23],
       [ 0.0000000e+00,  4.7884216e+11, -0.0000000e+00,  0.0000000e+00,
        -0.0000000e+00]], dtype=float32)

### Operator Pembagian Bulat

In [117]:
print("HASIL PEMBAGIAN BULAT ANTARA RANDOM_TENSOR & PRIME_TENSOR : ")
pembagian_bulat = random_tensor // prime_tensor
pembagian_bulat.numpy()

HASIL PEMBAGIAN BULAT ANTARA RANDOM_TENSOR & PRIME_TENSOR : 


array([[-1., -1.,  0.,  0., -1.],
       [ 0.,  0., -1.,  0.,  0.],
       [-1.,  0.,  0.,  0.,  0.],
       [-1., -1.,  0., -1., -1.],
       [ 0.,  0., -1.,  0., -1.]], dtype=float32)

## 5. Menampilkan nilai maksimum dan minimum dari variable random_tensor

### Nilai Maksimum Variable random_tensor

In [118]:
max_random_tensor = tf.argmax(random_tensor, axis = 0)
print("Nilai Maksimum Variable Random Tensor Terletak DiIndex ", max_random_tensor.numpy())
print("Untuk Baris Ke-1 nilai maksimumnya terletak diindex ke ", max_random_tensor[0].numpy())
print("Untuk Baris Ke-2 nilai maksimumnya terletak diindex ke ", max_random_tensor[1].numpy())
print("Untuk Baris Ke-3 nilai maksimumnya terletak diindex ke ", max_random_tensor[2].numpy())
print("Untuk Baris Ke-4 nilai maksimumnya terletak diindex ke ", max_random_tensor[3].numpy())
print("Untuk Baris Ke-5 nilai maksimumnya terletak diindex ke ", max_random_tensor[4].numpy())

Nilai Maksimum Variable Random Tensor Terletak DiIndex  [1 4 3 1 1]
Untuk Baris Ke-1 nilai maksimumnya terletak diindex ke  1
Untuk Baris Ke-2 nilai maksimumnya terletak diindex ke  4
Untuk Baris Ke-3 nilai maksimumnya terletak diindex ke  3
Untuk Baris Ke-4 nilai maksimumnya terletak diindex ke  1
Untuk Baris Ke-5 nilai maksimumnya terletak diindex ke  1


### Nilai Minimum Variable random_tensor

In [119]:
min_random_tensor= tf.argmin(random_tensor, axis = 0)
print("Nilai Minimum Variable Random Tensor Terletak DiIndex ", min_random_tensor.numpy())
print("Untuk Baris Ke-1 nilai minimumnya terletak diindex ke ", min_random_tensor[0].numpy())
print("Untuk Baris Ke-2 nilai minimumnya terletak diindex ke ", min_random_tensor[1].numpy())
print("Untuk Baris Ke-3 nilai minimumnya terletak diindex ke ", min_random_tensor[2].numpy())
print("Untuk Baris Ke-4 nilai minimumnya terletak diindex ke ", min_random_tensor[3].numpy())
print("Untuk Baris Ke-5 nilai minimumnya terletak diindex ke ", min_random_tensor[4].numpy())

Nilai Minimum Variable Random Tensor Terletak DiIndex  [3 3 1 3 3]
Untuk Baris Ke-1 nilai minimumnya terletak diindex ke  3
Untuk Baris Ke-2 nilai minimumnya terletak diindex ke  3
Untuk Baris Ke-3 nilai minimumnya terletak diindex ke  1
Untuk Baris Ke-4 nilai minimumnya terletak diindex ke  3
Untuk Baris Ke-5 nilai minimumnya terletak diindex ke  3


## 6. Menampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [120]:
concat_random_prime = tf.concat([random_tensor, prime_tensor], axis =0)
concat_random_prime

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-9.7603971e-01, -7.1492362e-01,  7.3386455e-01,  2.8581223e-01,
        -2.3028025e-02],
       [ 6.5786040e-01,  4.0351585e-01, -1.0177003e+00,  1.5687829e+00,
         1.3205584e+00],
       [-1.0235384e+00,  4.0732396e-01,  4.6989402e-01,  6.0693169e-01,
         7.5923777e-01],
       [-1.4553891e+00, -9.2807668e-01,  2.2096760e+00, -5.3177319e-02,
        -4.8170620e-01],
       [ 5.6924503e-03,  1.4055637e+00, -3.1561458e-01,  1.1607781e-02,
        -3.5126269e-01],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

## 7. Menampilkan hasil sorting dari kedua variable di atas (descending)

### Sorting Descending Variable random_tensor

In [121]:
random_tensor_desc = tf.sort(random_tensor, direction="DESCENDING")
print("RANDOM TENSOR BERDASARKAN SORTING DESCENDING")
random_tensor_desc.numpy()

RANDOM TENSOR BERDASARKAN SORTING DESCENDING


array([[ 0.73386455,  0.28581223, -0.02302803, -0.7149236 , -0.9760397 ],
       [ 1.5687829 ,  1.3205584 ,  0.6578604 ,  0.40351585, -1.0177003 ],
       [ 0.75923777,  0.6069317 ,  0.46989402,  0.40732396, -1.0235384 ],
       [ 2.209676  , -0.05317732, -0.4817062 , -0.9280767 , -1.4553891 ],
       [ 1.4055637 ,  0.01160778,  0.00569245, -0.31561458, -0.3512627 ]],
      dtype=float32)

### Sorting Descending Variable prime_tensor

In [122]:
prime_tensor_desc = tf.sort(prime_tensor, direction="DESCENDING")
print("PRIME TENSOR BERDASARKAN SORTING DESCENDING")
prime_tensor_desc.numpy()

PRIME TENSOR BERDASARKAN SORTING DESCENDING


array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [71., 67., 61., 59., 53.],
       [97., 89., 83., 79., 73.]], dtype=float32)